version: '3'

volumes:
  production_traefik: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gallon_production_traefik
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"

networks:
  proxy:
    external: true