log:
    level: INFO
  
  entryPoints:
    web:
      # http
      address: ":80"
  
    web-secure:
      # https
      address: ":443"
  
  api: {}
  
  certificatesResolvers:
    letsencrypt:
      # https://docs.traefik.io/master/https/acme/#lets-encrypt
      acme:
        email: "lpillaga@gmail.com"
        storage: /etc/traefik/acme/acme.json
        # https://docs.traefik.io/master/https/acme/#httpchallenge
        httpChallenge:
          entryPoint: web
  
  http:
    routers:
      api:
        rule: "Host(`traefik.elgallonegroec.com`)"
        entryPoints:
          - web
        middlewares:
          - redirect
          - csrf
          - myAuth
        service: api@internal
  
      api-secure:
        rule: "Host(`traefik.elgallonegroec.com`)"
        entryPoints:
          - web-secure
        middlewares:
          - csrf
        service: api@internal
        tls:
          # https://docs.traefik.io/master/routing/routers/#certresolver
          certResolver: letsencrypt
  
      admin-angular:
        rule: "Host(`admin.elgallonegroec.com`)"
        entryPoints:
          - web-secure
        middlewares:
          - redirect
          - csrf
        service: admin-angular
  
      admin-angular-secure:
        rule: "Host(`admin.elgallonegroec.com`)"
        entryPoints:
          - web-secure
        middlewares:
          - csrf
        service: admin-angular
        tls:
          # https://docs.traefik.io/master/routing/routers/#certresolver
          certResolver: letsencrypt 
  
      web-router:
        rule: "Host(`graphql.elgallonegroec.com`)"
        entryPoints:
          - web
        middlewares:
          - redirect
          - csrf
        service: django
  
      web-secure-router:
        rule: "Host(`graphql.elgallonegroec.com`)"
        entryPoints:
          - web-secure
        middlewares:
          - csrf
        service: django
        tls:
          # https://docs.traefik.io/master/routing/routers/#certresolver
          certResolver: letsencrypt
  
    middlewares:
      myAuth:
        basicAuth:
          users:
            - "admin:$apr1$bB31Nltd$kZvJ9pYV.PI3f2CGNSzLV."
      redirect:
        # https://docs.traefik.io/master/middlewares/redirectscheme/
        redirectScheme:
          scheme: https
          permanent: true
      csrf:
        # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
        # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
        headers:
          hostsProxyHeaders: ['X-CSRFToken']
  
    services:
      admin-angular:
        loadBalancer:
          servers:
            - url: http://admin-angular
  
      django:
        loadBalancer:
          servers:
            - url: http://django:5000
  
  
  providers:
    docker:
      endpoint: "unix:///var/run/docker.sock"
      network: proxy
      watch: true
    # https://docs.traefik.io/master/providers/file/
    file:
      filename: /etc/traefik/traefik.yml
      watch: true